var nano = require('nano')('http://115.146.85.141:5984');
var db = nano.use('travel_stats');
var travelJson = require('../harvest/constant/locations/travel');

var cities = [
    "Northland",
    "Waitangi Treaty Grounds",
    "The Kauri Museum",
    "Tane Mahuta Waipoua Forest",
    "Ninety Mile Beach",
    "Pompallier Mission and Printery",
    "Paihia",
    "Matakohe",
    "Opononi",
    "Paihia Harbour ",
    "Whangarei Falls",
    "Rainbow Falls",
    "The Stone Store",
    "Town Basin",
    "Whangarei Quarry Gardens",
    "Flagstaff Hill ",
    "Haruru Falls",
    "Christ Church",
    "The Parrot Place",
    "Poor Knights Island Marine Reserve",
    "Auckland ",
    "Tiritiri Matangi Island",
    "Auckland Museum",
    "Cornwall Park",
    "Sky Towe",
    "Waitakere Ranges",
    "Rangitoto Island",
    "Mount Eden",
    "Devonport",
    "Viaduct Harbou",
    "Auckland Zoo",
    "Waiheke Island",
    "One Tree Hill",
    "Kelly Tarlton's Sea Life Aquarium",
    "Hamilton Gardens",
    "Waikato",
    "Cathedral Cove",
    "Huka Falls",
    "Orakei Korako Cave",
    "Thermal Park ",
    "Caveworld",
    "Karangahake Gorge",
    "The Lost Spring",
    "Aratiatia Rapids",
    "Waitomo Glowworm Caves",
    "The Waterworks",
    "Hot Water Beach",
    "Huka Prawn Park",
    "Bay of Plenty",
    "Mount Maunganui Summit Track",
    "Redwoods",
    "Whakarewarewa Forest",
    "Tamaki Maori Village ",
    "Maunganui Beach",
    "OGO Rotorua",
    "Blue Lake",
    "Rotorua Museum",
    "Whakarewarewa",
    "Paradise Valley Springs Wildlife Park",
    "Agrodome",
    "Rainbow Springs Nature Park",
    "Kuirau Park",
    "Lake Rotorua",
    "Buried Village of Te Wairoa",
    "Gisborne",
    "East Cape Lighthouse",
    "Te Mata Peak",
    "Marine Parade",
    "Bluff Hill Lookout",
    "Mission Estate Winery",
    "Hawke's Bay",
    "Taranaki",
    "Pukekura Park ",
    "Coastal Walkway",
    "Mount Taranaki",
    "New Plymouth",
    "Puke Ariki",
    "Manawatu-Wanganui",
    "Tongariro National Park",
    "Forgotten World Adventures",
    "Mount Ruapehu",
    "Virginia Lake",
    "Victoria Esplanade Gardens",
    "Whakapapa",
    "Whanganui Rive",
    "Whakapapa Ski Resort",
    "Wellington",
    "Museum of New Zealand",
    "The Great War Exhibition",
    "Wellington Botanic Garden",
    "Mount Victoria",
    "ZEALANDIA Sanctuary",
    "Staglands Wildlife Reserve",
    "Oriental Bay",
    "Wellington Zoo",
    "Wellington Museum",
    "Wellington Cable Car",
    "Interislander Cook Strait Ferry",
    "Cuba Street District",
    "Space Place at Carter Observatory",
    "Tasman",
    "Abel Tasman National Park",
    "World of WearableArt",
    "Classic Cars Museum",
    " Kaiteriteri Beach",
    "Founders Park",
    "Picton",
    "Nelson",
    "Marlborough",
    "Marlborough Sounds",
    "Omaka Aviation Heritage Centre",
    "Blenheim",
    "Queen Charlotte Track",
    "Cloudy Bay",
    "West Coast",
    "Pancake Rocks",
    "Franz Josef Glacier",
    "Cape Foulwind Seal Colony",
    "Fox Glacier",
    "Hokitika Beach",
    "Shantytown",
    "Canterbury",
    "Christchurch Botanic Gardens",
    "Lake Tekapo",
    "Lake Pukaki",
    "Ohau Waterfall Walk and Seal Pups",
    "Kaikoura",
    "The Giants House",
    "Peninsula Walkway",
    "Aoraki Mount Cook National Park",
    "Ohau Point Seal Colony",
    "Hagley Park",
    "185 Empty White Chairs",
    "Canterbury Museum",
    "Quake City ",
    "Willowbank Wildlife Reserve",
    "Christchurch Gondola ",
    "Cardboard Cathedral",
    "Church of the Good Shepherd",
    "Lake Tekapo",
    "Orana Wildlife Park",
    "Otago",
    "Toitu Otago Settlers Museum",
    "Dunedin",
    "Lake Wanaka",
    "Otago Peninsula",
    "Wanaka",
    "Olveston Historic Home",
    "Queenstown",
    "Walter Peak High Country Farm",
    "The Winery",
    "Kiwi Birdlife Park",
    "Arrowtown Village",
    "Coronet Peak",
    "Larnach Castle",
    "Mount Iron",
    "Speight’s Brewery",
    "The Remarkables Ski Area",
    "Southland",
    "Milford Sound",
    "Doubtful Sound",
    "Routeburn Track",
    "Fiordland National Park",
    "Ulva Island ",
    "E Hayes and Sons",
    "Te Anau",
    "Te Anau Glowworm Caves"
];

var attitudes = ["positive", "negative"];

var states = [
	"capital territory",
	"western australia",
	"new south wales",
	"queensland",
	"north territory",
	"victoria",
	"tasmania"
];

var doc = {
    "attitude": "positive",
    "to": {
        "continent": "oceania",
        "state": null,
        "country": "new zealand",
        "city": null
    },
    "from": {
        "country": "australia",
        "state": "new south wales",
        "city": "sydney"
    },
    "overseas": true
};

var amount = 5432;

for(var i = 0; i < amount; i++) {
	var state = states[Math.floor(Math.random()*states.length)];
	var attitude = attitudes[Math.floor(Math.random()*attitudes.length)];
	var city = cities[Math.floor(Math.random()*cities.length)];
	doc.from.state = state;
	doc.from.city = city;
	doc.attitude = attitude;
	console.log(doc);
}
db.insert(doc, function(err, body) {
    console.log(body);
});