var travelWords = ['airfare', 'airplane', 'airplanes', 'airport', 'airports', 'automobile', 'automobiles',
    'backpack', 'backpacks', 'baggage', 'baggages', 'bag', 'beaches', 'bicycles', 'bikes', 'boats', 'buses',
    'bags', 'beach', 'bicycle', 'bike', 'binoculars', 'boat', 'bus', 'cab', 'cabs', 'cabin', 'cabins', 'camera',
    'cameras', 'campground', 'campgrounds', 'camping', 'campings', 'car', 'cars', 'carry-on', 'chart', 'charts',
    'coast', 'coasts', 'cruise', 'cruises', 'currency', 'customs', 'depart', 'departed', 'departure', 'departures',
    'destination', 'destinations', 'downtime', 'drive', 'drove', 'driven', 'embark', 'embarked', 'excursion',
    'expedition', 'explore', 'explored', 'ferry', 'flew', 'flight', 'fly', 'foreign', 'foreigner', 'garment',
    'getaway', 'go', 'went', 'guide', 'guided', 'hiatus', 'highway', 'hike', 'hiked', 'holiday', 'holidays',
    'hostel', 'hostels', 'hotel', 'hotels', 'inn', 'inns', 'island', 'islands', 'itinerary', 'jet', 'jets',
    'journey', 'keepsake', 'keepsakes', 'knapsack', 'knapsacks', 'lake', 'lakes', 'landing', 'landings', 'leave',
    'left', 'leisure', 'lodge', 'lodges', 'lodging', 'luggage', 'luggages', 'map', 'maps', 'motel', 'motels',
    'mountains', 'mountain', 'museum', 'museums', 'national', 'liner', 'outdoors', 'overnight', 'pack', 'passage',
    'passport', 'passports', 'photo', 'photos', 'photograph', 'photographs', 'picture', 'pictures', 'plane',
    'planes', 'port', 'ports', 'postcard', 'postcards', 'recreation', 'relax', 'relaxed', 'relaxation', 'reservations',
    'reservation', 'resort', 'resorts', 'rest', 'restaurant', 'restaurants', 'return', 'returned', 'ride', 'room', 'rooms',
    'sack', 'safari', 'sail', 'scenery', 'schedule', 'scheduled', 'sea', 'seashore', 'ship', 'ships', 'shore', 'sights',
    'souvenir', 'souvenirs', 'stand-by', 'station', 'stay', 'stayed', 'subway', 'subways', 'suitcase', 'suitcases',
    'sunscreen', 'swim', 'swam', 'swimsuit', 'takeoff', 'taxi', 'tent', 'tents', 'ticket', 'tickets', 'tip', 'tips',
    'tote', 'tour', 'tours', 'tourist', 'tourists', 'trail', 'train', 'trains', 'tram', 'trams', 'tramway', 'translate',
    'translated', 'transportation', 'travel', 'travelled', 'traveled', 'traveling', 'travelling', 'trip', 'trips', 'trunk',
    'umbrella', 'umbrellas', 'unpack', 'vacation', 'vehicle', 'vehicles', 'video', 'videos', 'visa', 'visit', 'visited',
    'voyage', 'walk', 'walked', 'wander', 'wandered', 'waterfall', 'waterpack', 'weekend', 'yacht', 'zoo'
];

exports.list = travelWords;